name: chain_arithmetics
description: "Simple arithmetic, but be very fast."
publish_to: "none"

version: 1.0.2+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_list_plus: ^0.5.2
  audioplayers: ^6.6.0
  slang: ^4.14.0
  slang_flutter: ^4.14.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
