name: Build Windows Installer

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install yq
        run: choco install yq

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.11.4

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows application
        run: flutter build windows --release

      - name: Copy VC++ DLL files
        run: |
          cp windows/dlls/* build/windows/x64/runner/Release

      - name: Build executable build file (with Powershell)
        run: |
          $source = "${{ github.workspace }}\build\windows\x64\runner\Release"
          $destination = "${{ github.workspace }}\ChainArithmetics.zip"
          Compress-Archive -Path $source -DestinationPath $destination
        shell: pwsh

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChainArithmetics-${{ github.ref_name }}-x86_64.zip
          path: "${{ github.workspace }}\\ChainArithmetics.zip"
